- name:
  hosts: localhost
  connection: local
  vars:
    copy_perms: "774"
    server_name: "{{ lookup('env', 'SERVER_NAME') }}"
  vars_files:
    - "servers/servers.yml"

  roles:
    - role: configs
