- name:
  hosts: localhost
  connection: local
  vars:
    copy_perms: "774"
    server_name: "{{ lookup('env', 'SERVER_NAME') }}"

  tasks:
    - include_tasks: tasks/copy-configs.yml
    - include_vars:
        file: "servers/servers.yml"
        name: servers
