- name: Check whether src dir exists before copying
  local_action: "stat path={{ src }}"
  register: fileinfo

# TODO replace secrets
- name: Copy source to destination
  synchronize:
    src: "{{ src }}"
    dest: "{% if dest is defined %}{{ dest }}{% else %}/home/container{% endif %}"
  when: fileinfo.stat.exists
