# TODO replace secrets
- name: "Copy from {{ src }} to destination"
  synchronize:
    src: "{{ src }}"
    dest: "{% if dest is defined %}{{ dest }}{% else %}/home/container{% endif %}"
    rsync_opts: ["-i", "--size-only"]
    archive: false
    recursive: true
  register: files
- debug: var=files.stdout_lines
