- name: Copy server-specific configurations
  include_tasks: copy-dir.yml
  vars:
    src: "servers/{{ item }}/sync"
  loop: "{{ servers[server_name] }}"

- name: Copy templates
  include_tasks: template-dir.yml
  vars:
    templates_source: "servers/{{ item }}/templates"
  loop: "{{ servers[server_name] }}"
