- set_fact:
    template_destination: "{% if dest is defined %}{{ dest }}{% else %}{{ lookup('ansible.builtin.env', 'HOME') }}{% endif %}"

- name: Ensure directory structure exists
  file:
    path: '{{ templates_destination }}/{{ dir.path }}'
    state: directory
  with_filetree: '{{ templates_source }}'
  when: item.state == 'directory'
  loop_control:
    loop_var: dir

- name: Ensure files are populated from templates
  template:
    src: '{{ template.src }}'
    dest: '{{ templates_destination }}/{{ template.path | regex_replace(".j2$", "") }}'
  with_filetree: '{{ templates_source }}'
  when: item.state == 'file'
  loop_control:
    loop_var: template
